CREATE TABLE [dbo].[TBL_SUBJECTS]
(
	SUB_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	TYP_SUB_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	CAT_SUB_GUID_ID UNIQUEIDENTIFIER NULL,
	SUB_NAME VARCHAR(50),
	SUB_SYSTEM_NAME VARCHAR(50) UNIQUE,

	CONSTRAINT [FK_TBL_TYPE_SUBJEST_TBL_SUBJETS] FOREIGN KEY ([TYP_SUB_GUID_ID]) REFERENCES [dbo].[TBL_TYPE_SUBJECTS](TYP_SUB_GUID_ID),
	CONSTRAINT [FK_TBL_CATEGORY_SUBJECTS_TBL_SUBJECTS] FOREIGN KEY([CAT_SUB_GUID_ID]) REFERENCES [dbo].[TBL_CATEGORY_SUBJECTS](CAT_SUB_GUID_ID)
	
)
