CREATE TABLE [dbo].[TBL_STUDENTS] (
    [STD_GUID_ID]        UNIQUEIDENTIFIER NOT NULL,
    [STD_FIRST_NAME]     VARCHAR (50)     NOT NULL,
    [STD_SECOND_NAME]    VARCHAR (50)     NULL,
    [STD_SURNAME]        VARCHAR (50)     NOT NULL,
    [STD_SECOND_SURNAME] VARCHAR (50)     NULL,
    [STD_CODE]           VARCHAR (MAX)    NOT NULL,
    [STD_EMAIL]          VARCHAR (50)     NOT NULL,
    [GEN_GUID_ID]        UNIQUEIDENTIFIER NOT NULL,
    [ADD_GUID_ID]        UNIQUEIDENTIFIER NULL,
	[STA_STD_GUID_ID]    UNIQUEIDENTIFIER NOT NULL,
    [STD_PHOTO]          VARBINARY (MAX)  NOT NULL,
    [STD_PHONE]          VARCHAR (8)      NOT NULL,
    [STD_BIRTHDATE]      DATETIME         NOT NULL,
    CONSTRAINT [PK__TBL_STUD__8987ED1D63277B12] PRIMARY KEY CLUSTERED ([STD_GUID_ID] ASC),
    CONSTRAINT [FK_TBL_GENDER_STUDENT] FOREIGN KEY ([GEN_GUID_ID]) REFERENCES [dbo].[TBL_GENDER] ([GEN_GUID_ID]),
    CONSTRAINT [FK_TBL_STUDENT_TBL_ADDRESS] FOREIGN KEY ([ADD_GUID_ID]) REFERENCES [dbo].[TBL_ADDRESS] ([ADD_GUID_ID]),
	CONSTRAINT [FK_TBL_STUDENT_TBL_STATUS] FOREIGN KEY ([STA_STD_GUID_ID]) REFERENCES [dbo].[TBL_STATUS_STUDENT]([STA_STD_GUID_ID])
);


