CREATE TABLE [dbo].[TBL_CONFIGURATION] (
    [CONF_GUID_ID]        UNIQUEIDENTIFIER NOT NULL,
    [CONF_NAME_OF_SCHOOL] VARCHAR (100)    NOT NULL,
    [CONF_SHIELD]         VARBINARY (MAX)  NULL,
    [CONF_EMAIL]          VARCHAR (50)     NULL,
    [CONF_PHONE_NUMBER]   VARCHAR (10)     NULL,
    [ADD_GUID_ID]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__TBL_CONF] PRIMARY KEY CLUSTERED ([CONF_GUID_ID] ASC),
    CONSTRAINT [FK_ADD] FOREIGN KEY ([ADD_GUID_ID]) REFERENCES [dbo].[TBL_ADDRESS] ([ADD_GUID_ID])
);


