CREATE TABLE [dbo].[TBL_RELATIONSHIP_USER_ROLL]
(
	USE_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	ROL_GUID_ID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_TBL_USER_TBL_REL] FOREIGN KEY ([USE_GUID_ID]) REFERENCES [dbo].[TBL_USER]([USE_GUID_ID]),
	CONSTRAINT [FK_TBL_ROL_TBL_REL] FOREIGN KEY ([ROL_GUID_ID]) REFERENCES [dbo].[TBL_ROLL]([ROL_GUID_ID])
)
