CREATE TABLE [dbo].[TBL_MANAGER] (
    [MAN_GUID_ID]      UNIQUEIDENTIFIER NOT NULL,
    [CONF_GUID_ID]     UNIQUEIDENTIFIER NOT NULL,
    [PER_GUID_ID]      UNIQUEIDENTIFIER NOT NULL,
    [TYP_MAN_GUID_ID]  UNIQUEIDENTIFIER NOT NULL,
    [MAN_DATE_ENABLED] DATETIME         NOT NULL,
    [MAN_DATE_DISABLE] DATETIME         NULL,
    [MAN_STATUS]       BIT              NOT NULL,
    PRIMARY KEY CLUSTERED ([MAN_GUID_ID] ASC),
    CONSTRAINT [FK_TBL_MANAGER_TBL_CONFIGURATION] FOREIGN KEY ([CONF_GUID_ID]) REFERENCES [dbo].[TBL_CONFIGURATION] ([CONF_GUID_ID]),
    CONSTRAINT [FK_TBL_PERSONS] FOREIGN KEY ([PER_GUID_ID]) REFERENCES [dbo].[TBL_PERSONS] ([PER_GUID_ID]),
    CONSTRAINT [FK_TBL_TYPE_MANAGER] FOREIGN KEY ([TYP_MAN_GUID_ID]) REFERENCES [dbo].[TBL_TYPE_MANAGER] ([TYP_MAN_GUID_ID])
);

