CREATE TABLE [dbo].[TBL_TYPE_PERSONS]
(
	TYP_PER_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	TYP_PER_NAME VARCHAR(50) NOT NULL,
	TYP_PER_SYSTEM_NAME VARCHAR(50) NOT NULL,
	TYP_PER_DESCRIPTION VARCHAR(100) NOT NULL
)
