CREATE TABLE [dbo].[TBL_RELATIONSHIP_TEACHER_SUBJETS] (
    [PER_GUID_ID]     UNIQUEIDENTIFIER NOT NULL,
    [CAT_SUB_GUID_ID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [FK_TBL_PER_TBL_RELATIONSHIP_TEACHER] FOREIGN KEY ([PER_GUID_ID]) REFERENCES [dbo].[TBL_PERSONS] ([PER_GUID_ID]),
    CONSTRAINT [FK_TBL_RELATIONSHIP_TEACHER_SUBJETS_TBL_CATEGORY_SUBJECTS] FOREIGN KEY ([CAT_SUB_GUID_ID]) REFERENCES [dbo].[TBL_CATEGORY_SUBJECTS] ([CAT_SUB_GUID_ID])
);


