CREATE TABLE [dbo].[TBL_STUDY_PLANS]
(
	STD_PL_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	STD_PL_NAME VARCHAR(100) NOT NULL,
	STD_PL_ENABLED_DATE DATETIME NOT NULL,
	STD_PL_DISABLED_DATE DATETIME NULL,
	STD_PL_STATUS BIT NOT NULL,
	SCH_GRA_GUID_ID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_TBL_STY_PLAN] FOREIGN KEY ([SCH_GRA_GUID_ID]) REFERENCES [dbo].[TBL_SCHOOL_GRADE]([SCH_GRA_GUID_ID])
)
