CREATE TABLE [dbo].[TBL_STUDY_PLAN]
(
	STI_PL_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	SCH_GRA_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	STI_PL_NAME VARCHAR(100) NOT NULL,
	STI_PL_STATUS BIT NOT NULL
)
