CREATE TABLE [dbo].[TBL_MANAGER]
(
	MAN_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	CONF_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	GEN_INF_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	TYP_MAN_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	MAN_DATE_ENABLED DATETIME NOT NULL,
	MAN_DATE_DISABLE DATETIME NULL,
	MAN_STATUS BIT NOT NULL,

	CONSTRAINT [FK_TBL_CONFIGURATION] FOREIGN KEY ([CONF_GUID_ID]) REFERENCES [dbo].[TBL_CONFIGURATION] ([CONF_GUID_ID]),
	CONSTRAINT [FK_TBL_TYPE_MANAGER] FOREIGN KEY ([TYP_MAN_GUID_ID]) REFERENCES [dbo].[TBL_TYPE_MANAGER] ([TYP_MAN_GUID_ID]),
	CONSTRAINT [FK_TBL_GENERAL_INFORMATION] FOREIGN KEY ([GEN_INF_GUID_ID]) REFERENCES [dbo].[TBL_GENERAL_INFORMATION] ([GEN_INF_GUID_ID])

)