CREATE TABLE [dbo].[TBL_ENROLLMENT]
(
	ENR_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	STD_GUID_ID UNIQUEIDENTIFIER NOT NULL, 
	GRO_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	ENR_EANABLED_DATE DATETIME NOT NULL,
	ENR_DISABLED_DATE DATETIME NOT NULL,

	CONSTRAINT [FK_TBL_STUDENT_TBL_ENROLLMENT] FOREIGN KEY ([STD_GUID_ID]) REFERENCES [dbo].[TBL_STUDENTS]([STD_GUID_ID]),
	CONSTRAINT [FK_TBL_GROUP_TBL_ENROLLMENT] FOREIGN KEY ([GRO_GUID_ID]) REFERENCES [dbo].[TBL_GROUP](GRO_GUID_ID)
)
