CREATE TABLE [dbo].[TBL_TYPE_MANAGER]
(
	TYP_MAN_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	TYP_MAN_NAME VARCHAR(100) NOT NULL,
	TYP_MAN_SYS_NAME VARCHAR(100) NOT NULL,
	TYP_MAN_DESCRIPTION VARCHAR(100) NULL,
	TYP_MAN_STATUS BIT NOT NULL
)
