CREATE TABLE [dbo].[TBL_SCHOOL_GRADE]
(
	SCH_GRA_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ACD_LEV_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	SCH_GRA_NAME VARCHAR(20),

	CONSTRAINT [FK_TBL_ACD_LEV_TBL_SCH_GRAD] FOREIGN KEY ([ACD_LEV_GUID_ID]) REFERENCES [dbo].[TBL_ACADEMIC_LEVELS](ACD_LEV_GUID_ID)
)
