CREATE TABLE [dbo].[TBL_GROUP]
(
	GRO_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	SEC_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	STD_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	PER_GUID_ID UNIQUEIDENTIFIER NOT NULL, 
)
