CREATE TABLE [dbo].[TBL_LEVELS_TAUGHT]
(
	CONF_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	ACD_LEV_GUID_ID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_TBL_CONFIG_TBL_LEVELS] FOREIGN KEY ([CONF_GUID_ID]) REFERENCES [dbo].[TBL_CONFIGURATION](CONF_GUID_ID),
	CONSTRAINT [FK_TBL_ACADEMIC_LEV_TBL_LEVEKS] FOREIGN KEY ([ACD_LEV_GUID_ID]) REFERENCES [dbo].[TBL_ACADEMIC_LEVELS](ACD_LEV_GUID_ID)
)
