CREATE TABLE [dbo].[TBL_PERSONS]
(
	PER_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	PER_FIRST_NAME VARCHAR(50) NOT NULL,
	PER_SECOND_NAME VARCHAR(50) NULL,
	PER_SURNAME VARCHAR(50) NOT NULL,
	PER_ID_CARD VARCHAR(30) NOT NULL,
	GEN_GUID_ID UNIQUEIDENTIFIER NOT NULL, 
	ADD_GUID_ID UNIQUEIDENTIFIER NULL,
	TYP_PER_GUID_ID  UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_TBL_GENDER] FOREIGN KEY ([GEN_GUID_ID]) REFERENCES [dbo].[TBL_GENDER] ([GEN_GUID_ID]),
	CONSTRAINT [FK_TBL_TYPE_PERSONS] FOREIGN KEY ([TYP_PER_GUID_ID]) REFERENCES [dbo].[TBL_TYPE_PERSONS] ([TYP_PER_GUID_ID])
)
