CREATE TABLE [dbo].[TBL_CONFIGURATION]
(
	CONF_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	CONF_NAME_OF_SCHOOL VARCHAR(100) NOT NULL,
	CONF_SHIELD VARBINARY(MAX) NULL,
	CONF_EMAIL	VARCHAR(50) NULL,
	CONF_PHONE_NUMBER VARCHAR(10),
	ADD_GUID_ID UNIQUEIDENTIFIER NOT NULL
)
