CREATE TABLE [dbo].[TBL_RELATIONSHIP_SUBJECTS_PERSONS_BY_YEAR]
(
	REL_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	PER_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	SUB_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	REL_ENABLED_DATE DATETIME NOT NULL,
	REL_DISABLED_DATE DATETIME NULL,
	REL_STATUS BIT NOT NULL,

	CONSTRAINT [FK_TBL_PER_TBL_REL] FOREIGN KEY ([PER_GUID_ID]) REFERENCES [dbo].[TBL_PERSONS]([PER_GUID_ID]),
	CONSTRAINT [FK_TBL_SUBJECTS_TBL_REL] FOREIGN KEY ([SUB_GUID_ID]) REFERENCES [dbo].[TBL_SUBJECTS]([SUB_GUID_ID])
)
