CREATE TABLE [dbo].[TBL_SECTION]
(
	SEC_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	SEC_NAME VARCHAR(10) NOT NULL,
	SCH_GRA_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	SEC_ENABLED_DATE DATETIME NOT NULL,
	SEC_DISABLED_DATE DATETIME NULL,
	SEC_STATUS BIT NOT NULL,

	CONSTRAINT [FK_TBL_SCHOOL_GR_TBL_SECTION] FOREIGN KEY ([SCH_GRA_GUID_ID]) REFERENCES [dbo].[TBL_SCHOOL_GRADE]([SCH_GRA_GUID_ID])
)
