CREATE TABLE [dbo].[TBL_PERSONS]
(
	PER_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	PER_FIRST_NAME VARCHAR(50) NOT NULL,
	PER_SECOND_NAME VARCHAR(50) NULL,
	PER_SURNAME VARCHAR(50),
	PER_ID_CARD VARCHAR(30),
	ADD_GUID_ID UNIQUEIDENTIFIER NULL,
	TYP_PER_GUID_ID  UNIQUEIDENTIFIER NOT NULL
)
