CREATE TABLE [dbo].[TBL_PERSONS] (
    [PER_GUID_ID]     UNIQUEIDENTIFIER NOT NULL,
    [PER_FIRST_NAME]  VARCHAR (50)     NOT NULL,
    [PER_SECOND_NAME] VARCHAR (50)     NULL,
    [PER_SURNAME]     VARCHAR (50)     NOT NULL,
	[PER_SECOND_SURNAME]     VARCHAR (50)     NOT NULL,
    [PER_ID_CARD]     VARCHAR (30)     NOT NULL,
	[PER_PHONE_NUMBER] VARCHAR(10) NOT NULL,
	[PER_BIRTHDATE]        DATE NOT NULL,
    [GEN_GUID_ID]     UNIQUEIDENTIFIER NOT NULL,
    [ADD_GUID_ID]     UNIQUEIDENTIFIER NULL,
    [TYP_PER_GUID_ID] UNIQUEIDENTIFIER NOT NULL,
	[ACD_LEV_GUID_ID] UNIQUEIDENTIFIER NULL,
	[PER_PHOTO] VARBINARY(MAX) NULL,
    PRIMARY KEY CLUSTERED ([PER_GUID_ID] ASC),
    CONSTRAINT [FK_TBL_GENDER] FOREIGN KEY ([GEN_GUID_ID]) REFERENCES [dbo].[TBL_GENDER] ([GEN_GUID_ID]),
    CONSTRAINT [FK_TBL_PERSONS_TBL_ADDRESS] FOREIGN KEY ([ADD_GUID_ID]) REFERENCES [dbo].[TBL_ADDRESS] ([ADD_GUID_ID]),
    CONSTRAINT [FK_TBL_TYPE_PERSONS] FOREIGN KEY ([TYP_PER_GUID_ID]) REFERENCES [dbo].[TBL_TYPE_PERSONS] ([TYP_PER_GUID_ID]),
	CONSTRAINT [FK_TBL_ACADEMIC_LEV_TBL_PER] FOREIGN KEY ([ACD_LEV_GUID_ID]) REFERENCES [dbo].[TBL_ACADEMIC_LEVELS]([ACD_LEV_GUID_ID])
);


