CREATE TABLE [dbo].[TBL_USER] (
    [USE_GUID_ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	PER_GUID_ID UNIQUEIDENTIFIER NULL,
	STD_GUID_ID UNIQUEIDENTIFIER NULL,
	USE_LOGIN VARCHAR(100) NOT NULL, 
	USE_PASS VARCHAR(MAX) NOT NULL,
	USE_STATUS BIT NOT NULL, 
	CONSTRAINT [FK_TBL_STUDENT_TBL_USERS] FOREIGN KEY ([STD_GUID_ID]) REFERENCES [dbo].[TBL_STUDENTS]([STD_GUID_ID]),
	CONSTRAINT [FK_TBL_PERSONS_TBL_PERSONS] FOREIGN KEY ([PER_GUID_ID]) REFERENCES [dbo].[TBL_PERSONS]([PER_GUID_ID])
);

