CREATE TABLE [dbo].[TBL_RELATIONSHIP]
(
	STD_GUID_ID UNIQUEIDENTIFIER NOT NULL,
	PER_GUID_ID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_TBL_STUDENT_TBL_RELATION] FOREIGN KEY ([STD_GUID_ID]) REFERENCES [dbo].[TBL_STUDENTS]([STD_GUID_ID]),
	CONSTRAINT [FK_TBL_PERSONS_TBL_RELATION] FOREIGN KEY ([PER_GUID_ID]) REFERENCES [dbo].[TBL_PERSONS](PER_GUID_ID)
)
