CREATE TABLE [dbo].[TBL_MUNICIPALITY]
(
	MUN_GUID_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	MUN_NAME VARCHAR(30) NOT NULL,
	DEP_GUID_ID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_TBL_DEPARMENT] FOREIGN KEY ([DEP_GUID_ID]) REFERENCES [dbo].[TBL_DEPARMENT] ([DEP_GUID_ID])
)
